project:
  type: website

website:
  title: "GAA Project Group 5"
  navbar:
    left:
      - text: "Project Proposal"
        href: "Proposal/proposal.html"
      - text: "Hawker Centre Distribution"
        href: "Module1/HawkerCentreDistribution.html"
      - text: "Hawker Centre Proximity"
        href: "Module2/HawkerCentreProximity.html"
      - text: "Hawker Centre Accessibility"
        href: "Module3/HawkerCentreAccessibility.html"

    right:
      - text: "Home"
        href: "index.html"

format:
  html:
    theme: cosmo
    css: "styles.css"
    toc: true

editor: visual
