project:
  type: website

website:
  title: "GAA Project Group 5"
  navbar:
    left:
      - text: "Project Proposal"
        href: "Proposal/proposal.html"
    right:
      - text: "Home"
        href: "index.html"

format:
  html:
    theme: cosmo
    css: "styles.css"
    toc: true

editor: visual
