---
title: "GAA Group 5: Project Introduction"

authors: Aidan, Gerald, Kabeer
date: "`r Sys.Date()`"

execute: 
  eval: true
  echo: true
  message: false
  warning: false
  freeze: true
---

### Our Objective:

Culinary Crossroads aims to utilize spatial point patterns to enhance exploration of hawker centres in Singapore. Objectives include creating comprehensive maps of hawker centre locations, identifying regions with higher concentrations, and providing individual maps for detailed analysis. Integration of a user-friendly Shiny app allows users to indicate preferred regions for exploration. Additionally, the project categorizes hawker centre food by cuisine types and dietary preferences, enabling personalized food recommendations aligned with user tastes and dietary restrictions. Overall, the objectives seek to provide a tailored and user-friendly platform for discovering culinary delights in Singapore's vibrant hawker culture.

### Steps in this Project :

-   Data Collection and Wrangling:

    -   Gather geospatial data on hawker centre locations, cuisine types, dietary types in Singapore.

-   Building the functions

    -   **Module 1: 1st Order Analysis - Density and Distribution of Hawker Centres**

        **\[Done by: Gerald\]**

        -   Map Creation: Develop a map displaying all hawker centres in Singapore.

        -   KDE 1st Order Analysis: Perform Kernel Density Estimation (KDE) to analyze the density and distribution of hawker centres across Singapore.

        -   Regional Maps: Provide individual maps for each region to further analyze hawker centre distribution.

        -   Shiny App Integration: Integrate a Shiny app allowing users to indicate (input) their preferred region for hawker centre exploration.

    -   **Module 2: 2nd Order Analysis - Hawker Centre Proximity**

        **\[Done by: Kabeer\]**

        -   Spatial Clustering Analysis: Perform spatial clustering analysis to identify clusters of hawker centres based on proximity.
        -   Distance Calculation: Calculate the distances between hawker centres within each cluster to assess how closely they are grouped together.
        -   Visualization: Visualize the clustering results on a map to illustrate the spatial distribution and proximity of hawker centres.
        -   Interpretation: Interpret the clustering patterns to understand the spatial relationships between hawker centres and identify areas with high and low concentrations.
        -   Shiny App Integration: Integrate a Shiny app allowing users to indicate (input) their preferred region for hawker centre exploration.

    -   **Module 3: Geographic Accessibility Modeling of Hawker Centres**

        **\[Done by: Aidan\]**

        -   MRT Station Selection: Allow users to select their preferred MRT station as a reference point for geographic accessibility analysis.
        -   Buffer Creation: Create buffer zones around the selected MRT station to represent areas of influence or accessibility.
        -   Hawker Centre Identification: Identify hawker centres located within the buffer zones to assess their accessibility from the chosen MRT station.
        -   Distance Calculation: Calculate the distances between the selected MRT station and nearby hawker centres to quantify accessibility.
        -   Shiny App Integration: Integrate a Shiny app allowing users to indicate (input) their preferred MRT station for hawker centre exploration, and it's accessibility to nearby hawker centres.

### Benefits:

-   The project offers numerous benefits, including facilitating exploration of Singapore's diverse hawker culture through user-friendly maps and personalized recommendations. By highlighting regions with higher concentrations of hawker centres and categorizing food options based on cuisine types and dietary preferences, users can easily discover culinary delights tailored to their tastes. The integration of a Shiny app enhances user engagement and interaction, allowing for seamless navigation and exploration of hawker centres. Ultimately, the project promotes cultural exploration, enhances user experience, and fosters a vibrant community of food enthusiasts in Singapore.

### Data Sources

Where can we find the data ?

-   OpenStreetMap (OSM): OpenStreetMap is a collaborative project that provides free and editable geospatial data. You can extract data related to restaurant locations, types, and user reviews.
-   Singapore Open Data (data.gov.sg): Hawker Centre Locations (kml)
-   DBS PayLah: Dataset with the list of stalls in each hawker centre
-   Google Places API: Google Places API allows you to retrieve information about places, including restaurants. You can obtain details such as place names, addresses, ratings, and reviews.
